⏪ Revert "⬆️ Upgrade Python version and dependencies"
This reverts commit ba35e3f59e25a386bcf85daf2ca8aace26ca47f2.

Caused AWS Lambda to crash with following error:
Error: Runtime exited with error: signal: segmentation fault Runtime.ExitError